### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by xslancovan** [MartinStyk/BachelorThesis#1]
Z..zelený stĺpec, C..červený stĺpec, prvé je číslo riadku, píšem správne výrazy, [].. poznámky

31C kategórii
43Z kategórii
       dekomprimácii
47Z Pred prístupom k~súboru \zv{CERT.RSA}, ktorý [chýba čiarka]
55Z aplikácii
4Z limitáciám [?]

**Comment by MartinStyk** [comment]
Opravene, dakujem
